theme: jekyll-theme-cayman
locale: en-US
title: "Josh's pages"
description: "A collection of resources"
baseurl: ""
url: https://jrsacher.github.io
author:
  name: Joshua Sacher
  email: github_pages@jrsacher.com
